# Generated by Django 5.2.8 on 2025-11-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRENAMIENTO', 'Entrenamiento'), ('PRUEBA', 'Prueba')], default='ENTRENAMIENTO', max_length=20)),
                ('ecuacion_str', models.CharField(max_length=255)),
                ('solucion', models.CharField(max_length=50)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='api.modeloejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='PasoResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paso', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('ecuacion_resultante', models.CharField(max_length=255)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='api.ejercicio')),
            ],
            options={
                'ordering': ['numero_paso'],
            },
        ),
    ]
