# Generated by Django 5.2.8 on 2025-11-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloejercicio',
            name='con_fracciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modeloejercicio',
            name='con_parentesis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modeloejercicio',
            name='incognita_una_vez',
            field=models.BooleanField(default=False),
        ),
    ]
