# Generated by Django 5.2.8 on 2025-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modeloejercicio_con_fracciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloejercicio',
            name='incognita_mas_de_una_vez',
            field=models.BooleanField(default=False),
        ),
    ]
