# Generated by Django 5.2.8 on 2025-12-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_progresousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresousuario',
            name='ejercicios_completados',
            field=models.ManyToManyField(blank=True, to='api.ejercicio'),
        ),
    ]
